"""empty message

Revision ID: 28bdcce6beb5
Revises: cc14cbe60deb
Create Date: 2020-05-10 19:15:57.552849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28bdcce6beb5'
down_revision = 'cc14cbe60deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('id_user', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword', 'id_user')
    # ### end Alembic commands ###
