"""empty message

Revision ID: 39e9271c99e3
Revises: 973fdfc93d05
Create Date: 2020-05-09 17:39:51.026735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e9271c99e3'
down_revision = '973fdfc93d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('story', sa.String(length=140), nullable=True))
    op.add_column('news', sa.Column('story', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'story')
    op.drop_column('article', 'story')
    # ### end Alembic commands ###
