"""added pic_link and also date into news database

Revision ID: 9d09e3f4eb21
Revises: bceb531e5734
Create Date: 2020-04-22 23:48:05.862442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d09e3f4eb21'
down_revision = 'bceb531e5734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('date', sa.String(length=140), nullable=True))
    op.add_column('news', sa.Column('pic_link', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'pic_link')
    op.drop_column('news', 'date')
    # ### end Alembic commands ###
