"""changed primary key in news to id

Revision ID: a0acc7a608ab
Revises: 13d057aa8c3c
Create Date: 2020-04-08 18:38:03.065352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0acc7a608ab'
down_revision = '13d057aa8c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('news', 'title',
    #             existing_type=sa.VARCHAR(length=140),
    #             nullable=True)
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('news', 'title',
    #            existing_type=sa.VARCHAR(length=140),
    #            )
    # ### end Alembic commands ###
    pass
