"""empty message

Revision ID: a708950e14be
Revises: 39e9271c99e3
Create Date: 2020-05-09 18:07:56.632879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a708950e14be'
down_revision = '39e9271c99e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('category', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'category')
    # ### end Alembic commands ###
