"""added id to the news database

Revision ID: c9154def00cc
Revises: 539657e48fd1
Create Date: 2020-04-08 17:10:19.898461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9154def00cc'
down_revision = '539657e48fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('news', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('news', 'id')
    # ### end Alembic commands ###
    pass
